### PR TITLE
add new functions to load scores

### PR DESCRIPTION
**Pull request by 183amir**
using numpy which is much faster and easier

### CODE REVIEW

**Comment by 183amir** [comment]
If someone could review this pull and merge it, I would appreciate it.

**Comment by tiagofrepereira2012** [comment]
I have nothing to say.
The code is cleaner. For me, you can merge it.

**Comment by siebenkopf** [comment]
I like your new functions. However, they lack documentation. Could you please update the documentation so that they follow the documentation style that we have developed, i.e., document all parameters and return values, including their required type?

As Andre use to say: code without documentation is worthless.

**Comment by 183amir** [comment]
I want them to be public and they have documentation but I am not familiar with Sphinx documentation style. I will update the documentation again once I have more experience with Sphinx.

**Pull request merged**
