### PR TITLE
Fixes UserWarning: Module bob was already imported from ...

### PR DESCRIPTION
**Pull request by 183amir**

### CODE REVIEW

**Comment by tiagofrepereira2012** [comment]
Hey Amir,

@pkorshunov removed these items that you are introducing few months ago.
https://github.com/bioidiap/bob.measure/commit/928335ae44b658215849fe234a4e556414077f3c

As far as I remember we were facing problems with zc.buildout.
It was impossible to develop a package that was already in the system python (or a virtualenv).
Are you sure that this feature will still stand after this modification?

**Comment by 183amir** [comment]
Yes Tiago,

We are discussing it at idiap. Do you remember what was the problem exactly?
How can I reproduce it?

**Comment by tiagofrepereira2012** [comment]
Just clone one bob package (this one per example) and bootstrap it using
bob stable, like this

git clone https://github.com/bioidiap/bob.measure/
cd bob.measure
/idiap/group/torch5spro/releases/bob-stable/py27/bin/python
bootstrap-buildout.py
--setuptools-version 20.0
./bin/buildout

After, just use this script to print the path of the package

import bob.measure
print(bob.measure)

If the output of the print is the path from bob.stable, you have the issue.
If it is the one that you just cloned, you are ok to go



On Tue, Mar 8, 2016 at 4:45 PM, Amir <notifications@github.com> wrote:

> Yes Tiago,
>
> We are discussing it at idiap. Do you remember what was the problem
> exactly?
> How can I reproduce it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bioidiap/bob.measure/pull/7#issuecomment-193830237>.
>



-- 
Tiago

**Comment by 183amir** [comment]
Running exactly what you said on bob.extension (on the `importwarning` branch):
```
<module 'bob.extension' from 'bob/extension/__init__.py'>
```

Running exactly what you said on bob.blitz:
```
<module 'bob.blitz' from 'bob/blitz/__init__.py'>
<module 'bob.extension' from 'bob.blitz/src/bob.extension/bob/extension/__init__.pyc'>
```

Looks like I am importing the local copies. I used the default `buildout.cfg` for bob.extension and changed the `buildout.cfg` of bob.blitz to clone my branch `bob.extension = git https://github.com/bioidiap/bob.extension branch=importwarning`. But it also worked with the master branch of bob.extension.

**Comment by pkorshunov** [comment]
Hi,
I think you should try this for three-tier packages as well. And also, you
should make sure you use the 'clean' environment without working version of
bob (the one without your patch) installed somewhere.
-pavel

**Comment by tiagofrepereira2012** [comment]
Ok,

Just to reproduce the issue. 
If you remove the lines
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

from the __init__.py (https://github.com/bioidiap/bob.extension/blob/master/bob/__init__.py) you get which copy (I'm trying to reproduce the old issue)?

PS: Adding @siebenkopf  in copy, so he can follows the discussion

**Comment by 183amir** [comment]
@pkorshunov I am using `bob-stable` provided in idiap. So it should have bob packages installed without my patch.

**Comment by 183amir** [comment]
So here is the test on a 3 tier package: (I am doing a buildout on `bob.io.matlab`
```
>>> import bob.io.base
>>> bob.io.base
<module 'bob.io.base' from 'bob.io.matlab/src/bob.io.base/bob/io/base/__init__.pyc'>
>>> import bob.io.matlab
>>> bob.io.matlab
<module 'bob.io.matlab' from 'bob/io/matlab/__init__.py'>
```

**Comment by pkorshunov** [comment]
@183amir That what I mean. The bob-stable version is fine and will work correctly. Since you want to apply a bob-wide patch and test if it works, you should use the patched version to see if you can still find packages correctly. Of course bob-stable will work, it has the pkgutil fix we did a few months back.

**Comment by 183amir** [comment]
@tiagofrepereira2012 It works if remove those lines too:
```
<module 'bob.extension' from '/home/bob.extension/bob/extension/__init__.py'>
```
but this time path that is printed is an absolute path.

@pkorshunov I am not removing pkgutils. I am adding namespace declarations on top of it which is a combination that you guys never had before.

**Comment by 183amir** [comment]
OK. As @pkorshunov explained, these pulls are not good after all.
To reproduce the bug that these pulls reintroduces, you need to install these packages with this patch applied in an environment and try to develop using `buildout` and `mr.developer`.
For example, you want to develop `bob.io.matlab` AND `bob.io.base` using `buildout` (`bob.io.base` is pulled in the `src` folder using `mr.developer`) and you have `bob.io.matlab` and `bob.io.base` installed in your root enviornment (which does contain these import warning patches). Then, when you are in your top `buildout` folder (i.e. git folder of `bob.io.matlab`) and run `./bin/python` and try to import `bob.io.base`, the `bob.io.base` from your root environment gets imported instead of the one in your `./src/bob.io.base` folder even though that is in the path.

To prevent the warnings, you need to make sure all your packages get installed in one folder and not in their own egg folders. So your installed environment will look like this:
```
/home/amir/miniconda/envs/_build/lib/python2.7/site-packages/bob
├── ap
├── bio
│   ├── base
│   ├── face
│   ├── gmm
│   ├── spear
│   └── video
├── blitz
├── core
│   └── random
├── db
│   ├── arface
│   ├── atnt
│   ├── atvskeystroke
│   ├── avspoof
│   ├── banca
│   ├── base
│   ├── biosecure
│   ├── biosecurid
│   ├── casia_fasd
│   ├── casme2
│   ├── caspeal
│   ├── frgc
│   ├── gbu
│   ├── iris
│   ├── kboc16
│   ├── lfw
│   ├── livdet2013
│   ├── mnist
│   ├── mobio
│   ├── msu_mfsd_mod
│   ├── multipie
│   ├── nist_sre12
│   ├── replay
│   ├── scface
│   ├── utfvp
│   ├── verification
│   ├── voxforge
│   ├── wine
│   ├── xm2vts
│   └── youtube
├── extension
│   └── scripts
├── io
│   ├── audio
│   ├── base
│   ├── image
│   ├── matlab
│   └── video
├── ip
│   ├── base
│   ├── color
│   ├── draw
│   ├── facedetect
│   ├── flandmark
│   ├── gabor
│   └── optflow
├── learn
│   ├── activation
│   ├── boosting
│   ├── em
│   ├── libsvm
│   ├── linear
│   └── mlp
├── math
├── measure
└── sp
```

I will close this pull. If you guys see more of these pulls in other repositories, please close them.

**Pull request closed without merging**
